# TRABAJO FINAL MODULO 5
# NOMBRE : CÉSAR MAYTA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/ecom_data_transformed.csv')
df.head(10)

,gender,divorced,married,single,login_computer,login_mobile,login_phone,order_fashion,order_grocery,order_laptop,...,hour_spend,device_registered,satisfaction_score,number_address,complain,order_lastyear,coupon_used,order_count,days_lastorder,cashback_amount
0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,3.0,3.0,2.0,9.0,1.0,11.0,1.0,1.0,5.0,160.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,3.0,4.0,3.0,7.0,1.0,15.0,0.0,1.0,0.0,121.0
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,2.0,4.0,3.0,6.0,1.0,14.0,0.0,1.0,3.0,120.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,2.0,4.0,5.0,8.0,0.0,23.0,0.0,1.0,3.0,134.0
4,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,3.0,3.0,5.0,3.0,0.0,11.0,1.0,1.0,3.0,130.0
5,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,3.0,5.0,5.0,2.0,1.0,22.0,4.0,6.0,7.0,139.0
6,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,2.0,3.0,2.0,4.0,0.0,14.0,0.0,1.0,0.0,121.0
7,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,3.0,3.0,2.0,3.0,1.0,16.0,2.0,2.0,0.0,123.0
8,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,3.0,4.0,3.0,2.0,1.0,14.0,0.0,1.0,2.0,127.0
9,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,2.0,5.0,3.0,2.0,0.0,12.0,1.0,1.0,1.0,123.0

In [3]:
df.isnull().sum().sum()

np.int64(0)

In [4]:
corr_matrix = df.corr()
corr_churn = corr_matrix[['churn']].sort_values(by='churn',ascending=False)
corr_churn

                        churn
churn                1.000000
complain             0.250188
single               0.180847
order_mobile _phone  0.154387
order_phone          0.113364
device_registered    0.107939
satisfaction_score   0.105481
city_tier            0.084703
payment_cod          0.083933
login_phone          0.078916
distance             0.069544
payment_ewallet      0.055751
login_computer       0.051099
number_address       0.043931
gender               0.029264
payment_cc           0.028796
hour_spend           0.018816
payment_upi          0.004163
coupon_used         -0.001430
payment_cash        -0.006178
order_lastyear      -0.007075
order_fashion       -0.014871
order_count         -0.024038
divorced            -0.024934
payment_debit       -0.032453
order_others        -0.054903
payment_credit      -0.064131
order_grocery       -0.089575
login_mobile        -0.111639
order_laptop        -0.133353
married             -0.151024
cashback_amount     -0.154161
days_lastorder      -0.156152
tenure              -0.337831

In [5]:
cols = corr_churn.index.tolist()
cols.remove('churn')
cols

['complain',
 'single',
 'order_mobile _phone',
 'order_phone',
 'device_registered',
 'satisfaction_score',
 'city_tier',
 'payment_cod',
 'login_phone',
 'distance',
 'payment_ewallet',
 'login_computer',
 'number_address',
 'gender',
 'payment_cc',
 'hour_spend',
 'payment_upi',
 'coupon_used',
 'payment_cash',
 'order_lastyear',
 'order_fashion',
 'order_count',
 'divorced',
 'payment_debit',
 'order_others',
 'payment_credit',
 'order_grocery',
 'login_mobile',
 'order_laptop',
 'married',
 'cashback_amount',
 'days_lastorder',
 'tenure']

In [6]:
X = df[cols].values
y = df['churn'].values.reshape(-1,1)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)