# IMPORTAMOS LA LIBRERIA DE PANDAS

In [1]:
import pandas as pd

# CARGAMOS UN ARCHIVO CSV

In [2]:
df_books = pd.read_csv('/content/libros.csv')
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

# SLICING

## PARA VER LA FORMA DEL DATAFRAME

In [3]:
df_books.shape

(550, 7)

## PARA MOSTRAR LAS 10 PRIMER FILAS

In [4]:
df_books.head(10)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction

## PARA OBTENER SOLO DESDE LA FILA 0 HASTA LA FILA 1

In [5]:
df_books[0:2]

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [6]:
cols = ['Name','Author']
df_books[cols]

,Name,Author
0,10-Day Green Smoothie Cleanse,JJ Smith
1,11/22/63: A Novel,Stephen King
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson
3,1984 (Signet Classics),George Orwell
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids
...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero

# FILTROS CON LOC Y ILOC

In [7]:
df_books.loc[0:4,['Name','Year']]

                                                Name  Year
0                      10-Day Green Smoothie Cleanse  2016
1                                  11/22/63: A Novel  2011
2            12 Rules for Life: An Antidote to Chaos  2018
3                             1984 (Signet Classics)  2017
4  5,000 Awesome Facts (About Everything!) (Natio...  2019

In [8]:
df_books.iloc[0:4,0:3]

                                      Name              Author  User Rating
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7
1                        11/22/63: A Novel        Stephen King          4.6
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7
3                   1984 (Signet Classics)       George Orwell          4.7

# MANIPULACION DE DATOS

In [9]:
import numpy as np

## AGREGAMOS UNA NUEVA COLUMNA AL DATAFRAME

In [10]:
df_books['genero'] = np.nan
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre,genero
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,NaN
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,NaN
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,NaN
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,NaN
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,NaN
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,NaN
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,NaN
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,NaN
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,NaN
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,NaN

In [11]:
df_books.shape

(550, 8)

In [12]:
total_filas = df_books.shape[0]
total_filas

550

In [13]:
data = np.arange(0,total_filas)
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549])

In [14]:
df_books['indice'] = data
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre,genero,indice
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,NaN,0
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,NaN,1
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,NaN,2
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,NaN,3
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,NaN,4
...,...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,NaN,545
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,NaN,546
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,NaN,547
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,NaN,548
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,NaN,549

# ELIMINAMOS LA COLUMNAS GENERO

In [15]:
df_books.drop('genero',axis=1,inplace=True)
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre,indice
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,0
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,1
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,2
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,4
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,545
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,546
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,547
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,548
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,549

# ELIMINAMOS LA FILA 0

In [16]:
df_books.drop(0,axis=0,inplace=True)
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre,indice
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,1
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,2
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,4
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction,5
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,545
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,546
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,547
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,548
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,549

# FILTROS POR CONDICIONES

In [18]:
#condicion_mayor_2016 = df_books['Year'] > 2016
df_books[df_books['Year'] > 2016]

,Name,Author,User Rating,Reviews,Price,Year,Genre,indice
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,2
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,4
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction,7
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction,8
...,...,...,...,...,...,...,...,...
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction,544
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,545
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,547
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,548
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,549

# FUNCIONES ESTADISTICAS

In [19]:
df_books.describe()

       User Rating       Reviews       Price         Year      indice
count   549.000000    549.000000  549.000000   549.000000  549.000000
mean      4.618215  11943.451730   13.109290  2013.996357  275.000000
std       0.227161  11739.563236   10.849959     3.166889  158.626921
min       3.300000     37.000000    0.000000  2009.000000    1.000000
25%       4.500000   4028.000000    7.000000  2011.000000  138.000000
50%       4.700000   8580.000000   11.000000  2014.000000  275.000000
75%       4.800000  17044.000000   16.000000  2017.000000  412.000000
max       4.900000  87841.000000  105.000000  2019.000000  549.000000

# PARA VER LOS TIPOS DE DATOS

In [23]:
df_books.dtypes

Name            object
Author          object
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre           object
indice           int64
dtype: object

In [22]:
df_books.mean(numeric_only=True)

User Rating        4.618215
Reviews        11943.451730
Price             13.109290
Year            2013.996357
indice           275.000000
dtype: float64

In [24]:
df_books.median(numeric_only=True)

User Rating       4.7
Reviews        8580.0
Price            11.0
Year           2014.0
indice          275.0
dtype: float64

# AGRUPACIONES

# AGRUPAMOS POR AUTHOR Y MOSTRAMOS LA SUMATORIA

In [27]:
df_books.groupby('Author').sum(numeric_only=True).reset_index()

                         Author  User Rating  Reviews  Price  Year  indice
0              Abraham Verghese          9.2     9732     22  4021     113
1                Adam Gasiewski          4.4     3113      6  2017     232
2                 Adam Mansbach          4.8     9568      9  2011     133
3                     Adir Levy          4.8     8170     13  2019     529
4    Admiral William H. McRaven          4.7    10199     11  2017     227
..                          ...          ...      ...    ...   ...     ...
242             Walter Isaacson         13.7    18668     61  6040     817
243               William Davis          8.8    14994     12  4025    1063
244            William P. Young          9.2    39440     16  4026     919
245            Wizards RPG Team         14.4    50970     81  6054     798
246                Zhi Gang Sha          9.2      257     23  4022     378

[247 rows x 6 columns]